/**
 * EUI Icon Cache for Vite
 * AUTO-GENERATED by scripts/generate-icon-cache.cjs
 * 
 * This file registers ALL EUI icons plus their aliases to prevent
 * dynamic import failures. Any icon name used in the app will work.
 */
import { appendIconComponentCache } from '@elastic/eui/es/components/icon/icon'

import { icon as accessibility } from '@elastic/eui/es/components/icon/assets/accessibility'
import { icon as aggregate } from '@elastic/eui/es/components/icon/assets/aggregate'
import { icon as alert } from '@elastic/eui/es/components/icon/assets/alert'
import { icon as analyzeEvent } from '@elastic/eui/es/components/icon/assets/analyzeEvent'
import { icon as analyze_event } from '@elastic/eui/es/components/icon/assets/analyze_event'
import { icon as annotation } from '@elastic/eui/es/components/icon/assets/annotation'
import { icon as anomaly_chart } from '@elastic/eui/es/components/icon/assets/anomaly_chart'
import { icon as anomaly_swim_lane } from '@elastic/eui/es/components/icon/assets/anomaly_swim_lane'
import { icon as apm_trace } from '@elastic/eui/es/components/icon/assets/apm_trace'
import { icon as app_add_data } from '@elastic/eui/es/components/icon/assets/app_add_data'
import { icon as app_advanced_settings } from '@elastic/eui/es/components/icon/assets/app_advanced_settings'
import { icon as app_agent } from '@elastic/eui/es/components/icon/assets/app_agent'
import { icon as app_apm } from '@elastic/eui/es/components/icon/assets/app_apm'
import { icon as app_app_search } from '@elastic/eui/es/components/icon/assets/app_app_search'
import { icon as app_auditbeat } from '@elastic/eui/es/components/icon/assets/app_auditbeat'
import { icon as app_canvas } from '@elastic/eui/es/components/icon/assets/app_canvas'
import { icon as app_cases } from '@elastic/eui/es/components/icon/assets/app_cases'
import { icon as app_code } from '@elastic/eui/es/components/icon/assets/app_code'
import { icon as app_console } from '@elastic/eui/es/components/icon/assets/app_console'
import { icon as app_cross_cluster_replication } from '@elastic/eui/es/components/icon/assets/app_cross_cluster_replication'
import { icon as app_dashboard } from '@elastic/eui/es/components/icon/assets/app_dashboard'
import { icon as app_devtools } from '@elastic/eui/es/components/icon/assets/app_devtools'
import { icon as app_discover } from '@elastic/eui/es/components/icon/assets/app_discover'
import { icon as app_ems } from '@elastic/eui/es/components/icon/assets/app_ems'
import { icon as app_filebeat } from '@elastic/eui/es/components/icon/assets/app_filebeat'
import { icon as app_fleet } from '@elastic/eui/es/components/icon/assets/app_fleet'
import { icon as app_gis } from '@elastic/eui/es/components/icon/assets/app_gis'
import { icon as app_graph } from '@elastic/eui/es/components/icon/assets/app_graph'
import { icon as app_grok } from '@elastic/eui/es/components/icon/assets/app_grok'
import { icon as app_heartbeat } from '@elastic/eui/es/components/icon/assets/app_heartbeat'
import { icon as app_index_management } from '@elastic/eui/es/components/icon/assets/app_index_management'
import { icon as app_index_pattern } from '@elastic/eui/es/components/icon/assets/app_index_pattern'
import { icon as app_index_rollup } from '@elastic/eui/es/components/icon/assets/app_index_rollup'
import { icon as app_lens } from '@elastic/eui/es/components/icon/assets/app_lens'
import { icon as app_logs } from '@elastic/eui/es/components/icon/assets/app_logs'
import { icon as app_management } from '@elastic/eui/es/components/icon/assets/app_management'
import { icon as app_metricbeat } from '@elastic/eui/es/components/icon/assets/app_metricbeat'
import { icon as app_metrics } from '@elastic/eui/es/components/icon/assets/app_metrics'
import { icon as app_ml } from '@elastic/eui/es/components/icon/assets/app_ml'
import { icon as app_monitoring } from '@elastic/eui/es/components/icon/assets/app_monitoring'
import { icon as app_notebook } from '@elastic/eui/es/components/icon/assets/app_notebook'
import { icon as app_packetbeat } from '@elastic/eui/es/components/icon/assets/app_packetbeat'
import { icon as app_pipeline } from '@elastic/eui/es/components/icon/assets/app_pipeline'
import { icon as app_recently_viewed } from '@elastic/eui/es/components/icon/assets/app_recently_viewed'
import { icon as app_reporting } from '@elastic/eui/es/components/icon/assets/app_reporting'
import { icon as app_saved_objects } from '@elastic/eui/es/components/icon/assets/app_saved_objects'
import { icon as app_search_profiler } from '@elastic/eui/es/components/icon/assets/app_search_profiler'
import { icon as app_security } from '@elastic/eui/es/components/icon/assets/app_security'
import { icon as app_security_analytics } from '@elastic/eui/es/components/icon/assets/app_security_analytics'
import { icon as app_spaces } from '@elastic/eui/es/components/icon/assets/app_spaces'
import { icon as app_sql } from '@elastic/eui/es/components/icon/assets/app_sql'
import { icon as app_timelion } from '@elastic/eui/es/components/icon/assets/app_timelion'
import { icon as app_upgrade_assistant } from '@elastic/eui/es/components/icon/assets/app_upgrade_assistant'
import { icon as app_uptime } from '@elastic/eui/es/components/icon/assets/app_uptime'
import { icon as app_users_roles } from '@elastic/eui/es/components/icon/assets/app_users_roles'
import { icon as app_visualize } from '@elastic/eui/es/components/icon/assets/app_visualize'
import { icon as app_vulnerability_management } from '@elastic/eui/es/components/icon/assets/app_vulnerability_management'
import { icon as app_watches } from '@elastic/eui/es/components/icon/assets/app_watches'
import { icon as app_workflows } from '@elastic/eui/es/components/icon/assets/app_workflows'
import { icon as app_workplace_search } from '@elastic/eui/es/components/icon/assets/app_workplace_search'
import { icon as apps } from '@elastic/eui/es/components/icon/assets/apps'
import { icon as arrowEnd } from '@elastic/eui/es/components/icon/assets/arrowEnd'
import { icon as arrowStart } from '@elastic/eui/es/components/icon/assets/arrowStart'
import { icon as arrow_down } from '@elastic/eui/es/components/icon/assets/arrow_down'
import { icon as arrow_left } from '@elastic/eui/es/components/icon/assets/arrow_left'
import { icon as arrow_right } from '@elastic/eui/es/components/icon/assets/arrow_right'
import { icon as arrow_up } from '@elastic/eui/es/components/icon/assets/arrow_up'
import { icon as article } from '@elastic/eui/es/components/icon/assets/article'
import { icon as asterisk } from '@elastic/eui/es/components/icon/assets/asterisk'
import { icon as at } from '@elastic/eui/es/components/icon/assets/at'
import { icon as background_task } from '@elastic/eui/es/components/icon/assets/background_task'
import { icon as bell } from '@elastic/eui/es/components/icon/assets/bell'
import { icon as bellSlash } from '@elastic/eui/es/components/icon/assets/bellSlash'
import { icon as beta } from '@elastic/eui/es/components/icon/assets/beta'
import { icon as bolt } from '@elastic/eui/es/components/icon/assets/bolt'
import { icon as boxes_horizontal } from '@elastic/eui/es/components/icon/assets/boxes_horizontal'
import { icon as boxes_vertical } from '@elastic/eui/es/components/icon/assets/boxes_vertical'
import { icon as branch } from '@elastic/eui/es/components/icon/assets/branch'
import { icon as branchUser } from '@elastic/eui/es/components/icon/assets/branchUser'
import { icon as broom } from '@elastic/eui/es/components/icon/assets/broom'
import { icon as brush } from '@elastic/eui/es/components/icon/assets/brush'
import { icon as bug } from '@elastic/eui/es/components/icon/assets/bug'
import { icon as bullseye } from '@elastic/eui/es/components/icon/assets/bullseye'
import { icon as calendar } from '@elastic/eui/es/components/icon/assets/calendar'
import { icon as change_point_detection } from '@elastic/eui/es/components/icon/assets/change_point_detection'
import { icon as check } from '@elastic/eui/es/components/icon/assets/check'
import { icon as checkCircle } from '@elastic/eui/es/components/icon/assets/checkCircle'
import { icon as checkInCircleFilled } from '@elastic/eui/es/components/icon/assets/checkInCircleFilled'
import { icon as cheer } from '@elastic/eui/es/components/icon/assets/cheer'
import { icon as clickLeft } from '@elastic/eui/es/components/icon/assets/clickLeft'
import { icon as clickRight } from '@elastic/eui/es/components/icon/assets/clickRight'
import { icon as clock } from '@elastic/eui/es/components/icon/assets/clock'
import { icon as clockCounter } from '@elastic/eui/es/components/icon/assets/clockCounter'
import { icon as cloudDrizzle } from '@elastic/eui/es/components/icon/assets/cloudDrizzle'
import { icon as cloudStormy } from '@elastic/eui/es/components/icon/assets/cloudStormy'
import { icon as cloudSunny } from '@elastic/eui/es/components/icon/assets/cloudSunny'
import { icon as cluster } from '@elastic/eui/es/components/icon/assets/cluster'
import { icon as code } from '@elastic/eui/es/components/icon/assets/code'
import { icon as color } from '@elastic/eui/es/components/icon/assets/color'
import { icon as comment } from '@elastic/eui/es/components/icon/assets/comment'
import { icon as compute } from '@elastic/eui/es/components/icon/assets/compute'
import { icon as console } from '@elastic/eui/es/components/icon/assets/console'
import { icon as container } from '@elastic/eui/es/components/icon/assets/container'
import { icon as continuityAbove } from '@elastic/eui/es/components/icon/assets/continuityAbove'
import { icon as continuityAboveBelow } from '@elastic/eui/es/components/icon/assets/continuityAboveBelow'
import { icon as continuityBelow } from '@elastic/eui/es/components/icon/assets/continuityBelow'
import { icon as continuityWithin } from '@elastic/eui/es/components/icon/assets/continuityWithin'
import { icon as contrast } from '@elastic/eui/es/components/icon/assets/contrast'
import { icon as contrastHigh } from '@elastic/eui/es/components/icon/assets/contrastHigh'
import { icon as controls } from '@elastic/eui/es/components/icon/assets/controls'
import { icon as copy } from '@elastic/eui/es/components/icon/assets/copy'
import { icon as copy_clipboard } from '@elastic/eui/es/components/icon/assets/copy_clipboard'
import { icon as cross } from '@elastic/eui/es/components/icon/assets/cross'
import { icon as crossInCircle } from '@elastic/eui/es/components/icon/assets/crossInCircle'
import { icon as cross_in_circle } from '@elastic/eui/es/components/icon/assets/cross_in_circle'
import { icon as crosshairs } from '@elastic/eui/es/components/icon/assets/crosshairs'
import { icon as currency } from '@elastic/eui/es/components/icon/assets/currency'
import { icon as cut } from '@elastic/eui/es/components/icon/assets/cut'
import { icon as database } from '@elastic/eui/es/components/icon/assets/database'
import { icon as desktop } from '@elastic/eui/es/components/icon/assets/desktop'
import { icon as diff } from '@elastic/eui/es/components/icon/assets/diff'
import { icon as document } from '@elastic/eui/es/components/icon/assets/document'
import { icon as documentEdit } from '@elastic/eui/es/components/icon/assets/documentEdit'
import { icon as documentation } from '@elastic/eui/es/components/icon/assets/documentation'
import { icon as documents } from '@elastic/eui/es/components/icon/assets/documents'
import { icon as dot } from '@elastic/eui/es/components/icon/assets/dot'
import { icon as dotInCircle } from '@elastic/eui/es/components/icon/assets/dotInCircle'
import { icon as doubleArrowLeft } from '@elastic/eui/es/components/icon/assets/doubleArrowLeft'
import { icon as doubleArrowRight } from '@elastic/eui/es/components/icon/assets/doubleArrowRight'
import { icon as download } from '@elastic/eui/es/components/icon/assets/download'
import { icon as editorDistributeHorizontal } from '@elastic/eui/es/components/icon/assets/editorDistributeHorizontal'
import { icon as editorDistributeVertical } from '@elastic/eui/es/components/icon/assets/editorDistributeVertical'
import { icon as editorItemAlignBottom } from '@elastic/eui/es/components/icon/assets/editorItemAlignBottom'
import { icon as editorItemAlignCenter } from '@elastic/eui/es/components/icon/assets/editorItemAlignCenter'
import { icon as editorItemAlignLeft } from '@elastic/eui/es/components/icon/assets/editorItemAlignLeft'
import { icon as editorItemAlignMiddle } from '@elastic/eui/es/components/icon/assets/editorItemAlignMiddle'
import { icon as editorItemAlignRight } from '@elastic/eui/es/components/icon/assets/editorItemAlignRight'
import { icon as editorItemAlignTop } from '@elastic/eui/es/components/icon/assets/editorItemAlignTop'
import { icon as editorPositionBottomLeft } from '@elastic/eui/es/components/icon/assets/editorPositionBottomLeft'
import { icon as editorPositionBottomRight } from '@elastic/eui/es/components/icon/assets/editorPositionBottomRight'
import { icon as editorPositionTopLeft } from '@elastic/eui/es/components/icon/assets/editorPositionTopLeft'
import { icon as editorPositionTopRight } from '@elastic/eui/es/components/icon/assets/editorPositionTopRight'
import { icon as editor_align_center } from '@elastic/eui/es/components/icon/assets/editor_align_center'
import { icon as editor_align_left } from '@elastic/eui/es/components/icon/assets/editor_align_left'
import { icon as editor_align_right } from '@elastic/eui/es/components/icon/assets/editor_align_right'
import { icon as editor_bold } from '@elastic/eui/es/components/icon/assets/editor_bold'
import { icon as editor_checklist } from '@elastic/eui/es/components/icon/assets/editor_checklist'
import { icon as editor_heading } from '@elastic/eui/es/components/icon/assets/editor_heading'
import { icon as editor_italic } from '@elastic/eui/es/components/icon/assets/editor_italic'
import { icon as editor_link } from '@elastic/eui/es/components/icon/assets/editor_link'
import { icon as editor_ordered_list } from '@elastic/eui/es/components/icon/assets/editor_ordered_list'
import { icon as editor_redo } from '@elastic/eui/es/components/icon/assets/editor_redo'
import { icon as editor_strike } from '@elastic/eui/es/components/icon/assets/editor_strike'
import { icon as editor_table } from '@elastic/eui/es/components/icon/assets/editor_table'
import { icon as editor_underline } from '@elastic/eui/es/components/icon/assets/editor_underline'
import { icon as editor_undo } from '@elastic/eui/es/components/icon/assets/editor_undo'
import { icon as editor_unordered_list } from '@elastic/eui/es/components/icon/assets/editor_unordered_list'
import { icon as email } from '@elastic/eui/es/components/icon/assets/email'
import { icon as empty } from '@elastic/eui/es/components/icon/assets/empty'
import { icon as endpoint } from '@elastic/eui/es/components/icon/assets/endpoint'
import { icon as eql } from '@elastic/eui/es/components/icon/assets/eql'
import { icon as eraser } from '@elastic/eui/es/components/icon/assets/eraser'
import { icon as error } from '@elastic/eui/es/components/icon/assets/error'
import { icon as errorFilled } from '@elastic/eui/es/components/icon/assets/errorFilled'
import { icon as esqlVis } from '@elastic/eui/es/components/icon/assets/esqlVis'
import { icon as exit } from '@elastic/eui/es/components/icon/assets/exit'
import { icon as expand } from '@elastic/eui/es/components/icon/assets/expand'
import { icon as expandMini } from '@elastic/eui/es/components/icon/assets/expandMini'
import { icon as exportIcon } from '@elastic/eui/es/components/icon/assets/export'
import { icon as eye } from '@elastic/eui/es/components/icon/assets/eye'
import { icon as eye_closed } from '@elastic/eui/es/components/icon/assets/eye_closed'
import { icon as face_happy } from '@elastic/eui/es/components/icon/assets/face_happy'
import { icon as face_neutral } from '@elastic/eui/es/components/icon/assets/face_neutral'
import { icon as face_sad } from '@elastic/eui/es/components/icon/assets/face_sad'
import { icon as field_statistics } from '@elastic/eui/es/components/icon/assets/field_statistics'
import { icon as filter } from '@elastic/eui/es/components/icon/assets/filter'
import { icon as filterExclude } from '@elastic/eui/es/components/icon/assets/filterExclude'
import { icon as filterIgnore } from '@elastic/eui/es/components/icon/assets/filterIgnore'
import { icon as filterInCircle } from '@elastic/eui/es/components/icon/assets/filterInCircle'
import { icon as filterInclude } from '@elastic/eui/es/components/icon/assets/filterInclude'
import { icon as flag } from '@elastic/eui/es/components/icon/assets/flag'
import { icon as flask } from '@elastic/eui/es/components/icon/assets/flask'
import { icon as fold } from '@elastic/eui/es/components/icon/assets/fold'
import { icon as folder_check } from '@elastic/eui/es/components/icon/assets/folder_check'
import { icon as folder_closed } from '@elastic/eui/es/components/icon/assets/folder_closed'
import { icon as folder_exclamation } from '@elastic/eui/es/components/icon/assets/folder_exclamation'
import { icon as folder_open } from '@elastic/eui/es/components/icon/assets/folder_open'
import { icon as frameNext } from '@elastic/eui/es/components/icon/assets/frameNext'
import { icon as framePrevious } from '@elastic/eui/es/components/icon/assets/framePrevious'
import { icon as fullScreenExit } from '@elastic/eui/es/components/icon/assets/fullScreenExit'
import { icon as full_screen } from '@elastic/eui/es/components/icon/assets/full_screen'
import { icon as functionIcon } from '@elastic/eui/es/components/icon/assets/function'
import { icon as gear } from '@elastic/eui/es/components/icon/assets/gear'
import { icon as globe } from '@elastic/eui/es/components/icon/assets/globe'
import { icon as grab } from '@elastic/eui/es/components/icon/assets/grab'
import { icon as grabOmnidirectional } from '@elastic/eui/es/components/icon/assets/grabOmnidirectional'
import { icon as grab_horizontal } from '@elastic/eui/es/components/icon/assets/grab_horizontal'
import { icon as gradient } from '@elastic/eui/es/components/icon/assets/gradient'
import { icon as grid } from '@elastic/eui/es/components/icon/assets/grid'
import { icon as heart } from '@elastic/eui/es/components/icon/assets/heart'
import { icon as heatmap } from '@elastic/eui/es/components/icon/assets/heatmap'
import { icon as help } from '@elastic/eui/es/components/icon/assets/help'
import { icon as home } from '@elastic/eui/es/components/icon/assets/home'
import { icon as image } from '@elastic/eui/es/components/icon/assets/image'
import { icon as importIcon } from '@elastic/eui/es/components/icon/assets/import'
import { icon as index } from '@elastic/eui/es/components/icon/assets/index'
import { icon as indexTemporary } from '@elastic/eui/es/components/icon/assets/indexTemporary'
import { icon as index_close } from '@elastic/eui/es/components/icon/assets/index_close'
import { icon as index_edit } from '@elastic/eui/es/components/icon/assets/index_edit'
import { icon as index_flush } from '@elastic/eui/es/components/icon/assets/index_flush'
import { icon as index_mapping } from '@elastic/eui/es/components/icon/assets/index_mapping'
import { icon as index_open } from '@elastic/eui/es/components/icon/assets/index_open'
import { icon as index_runtime } from '@elastic/eui/es/components/icon/assets/index_runtime'
import { icon as index_settings } from '@elastic/eui/es/components/icon/assets/index_settings'
import { icon as infinity } from '@elastic/eui/es/components/icon/assets/infinity'
import { icon as info } from '@elastic/eui/es/components/icon/assets/info'
import { icon as inputOutput } from '@elastic/eui/es/components/icon/assets/inputOutput'
import { icon as inspect } from '@elastic/eui/es/components/icon/assets/inspect'
import { icon as invert } from '@elastic/eui/es/components/icon/assets/invert'
import { icon as ip } from '@elastic/eui/es/components/icon/assets/ip'
import { icon as issue } from '@elastic/eui/es/components/icon/assets/issue'
import { icon as key } from '@elastic/eui/es/components/icon/assets/key'
import { icon as keyboard } from '@elastic/eui/es/components/icon/assets/keyboard'
import { icon as kql_field } from '@elastic/eui/es/components/icon/assets/kql_field'
import { icon as kql_function } from '@elastic/eui/es/components/icon/assets/kql_function'
import { icon as kql_operand } from '@elastic/eui/es/components/icon/assets/kql_operand'
import { icon as kql_selector } from '@elastic/eui/es/components/icon/assets/kql_selector'
import { icon as kql_value } from '@elastic/eui/es/components/icon/assets/kql_value'
import { icon as kubernetesNode } from '@elastic/eui/es/components/icon/assets/kubernetesNode'
import { icon as kubernetesPod } from '@elastic/eui/es/components/icon/assets/kubernetesPod'
import { icon as launch } from '@elastic/eui/es/components/icon/assets/launch'
import { icon as layers } from '@elastic/eui/es/components/icon/assets/layers'
import { icon as lettering } from '@elastic/eui/es/components/icon/assets/lettering'
import { icon as lineDashed } from '@elastic/eui/es/components/icon/assets/lineDashed'
import { icon as lineDotted } from '@elastic/eui/es/components/icon/assets/lineDotted'
import { icon as lineSolid } from '@elastic/eui/es/components/icon/assets/lineSolid'
import { icon as link } from '@elastic/eui/es/components/icon/assets/link'
import { icon as list } from '@elastic/eui/es/components/icon/assets/list'
import { icon as list_add } from '@elastic/eui/es/components/icon/assets/list_add'
import { icon as lock } from '@elastic/eui/es/components/icon/assets/lock'
import { icon as lockOpen } from '@elastic/eui/es/components/icon/assets/lockOpen'
import { icon as log_pattern_analysis } from '@elastic/eui/es/components/icon/assets/log_pattern_analysis'
import { icon as log_rate_analysis } from '@elastic/eui/es/components/icon/assets/log_rate_analysis'
import { icon as logo_aerospike } from '@elastic/eui/es/components/icon/assets/logo_aerospike'
import { icon as logo_apache } from '@elastic/eui/es/components/icon/assets/logo_apache'
import { icon as logo_app_search } from '@elastic/eui/es/components/icon/assets/logo_app_search'
import { icon as logo_aws } from '@elastic/eui/es/components/icon/assets/logo_aws'
import { icon as logo_aws_mono } from '@elastic/eui/es/components/icon/assets/logo_aws_mono'
import { icon as logo_azure } from '@elastic/eui/es/components/icon/assets/logo_azure'
import { icon as logo_azure_mono } from '@elastic/eui/es/components/icon/assets/logo_azure_mono'
import { icon as logo_beats } from '@elastic/eui/es/components/icon/assets/logo_beats'
import { icon as logo_business_analytics } from '@elastic/eui/es/components/icon/assets/logo_business_analytics'
import { icon as logo_ceph } from '@elastic/eui/es/components/icon/assets/logo_ceph'
import { icon as logo_cloud } from '@elastic/eui/es/components/icon/assets/logo_cloud'
import { icon as logo_cloud_ece } from '@elastic/eui/es/components/icon/assets/logo_cloud_ece'
import { icon as logo_code } from '@elastic/eui/es/components/icon/assets/logo_code'
import { icon as logo_codesandbox } from '@elastic/eui/es/components/icon/assets/logo_codesandbox'
import { icon as logo_couchbase } from '@elastic/eui/es/components/icon/assets/logo_couchbase'
import { icon as logo_docker } from '@elastic/eui/es/components/icon/assets/logo_docker'
import { icon as logo_dropwizard } from '@elastic/eui/es/components/icon/assets/logo_dropwizard'
import { icon as logo_elastic } from '@elastic/eui/es/components/icon/assets/logo_elastic'
import { icon as logo_elastic_stack } from '@elastic/eui/es/components/icon/assets/logo_elastic_stack'
import { icon as logo_elasticsearch } from '@elastic/eui/es/components/icon/assets/logo_elasticsearch'
import { icon as logo_enterprise_search } from '@elastic/eui/es/components/icon/assets/logo_enterprise_search'
import { icon as logo_etcd } from '@elastic/eui/es/components/icon/assets/logo_etcd'
import { icon as logo_gcp } from '@elastic/eui/es/components/icon/assets/logo_gcp'
import { icon as logo_gcp_mono } from '@elastic/eui/es/components/icon/assets/logo_gcp_mono'
import { icon as logo_github } from '@elastic/eui/es/components/icon/assets/logo_github'
import { icon as logo_gmail } from '@elastic/eui/es/components/icon/assets/logo_gmail'
import { icon as logo_golang } from '@elastic/eui/es/components/icon/assets/logo_golang'
import { icon as logo_google_g } from '@elastic/eui/es/components/icon/assets/logo_google_g'
import { icon as logo_haproxy } from '@elastic/eui/es/components/icon/assets/logo_haproxy'
import { icon as logo_ibm } from '@elastic/eui/es/components/icon/assets/logo_ibm'
import { icon as logo_ibm_mono } from '@elastic/eui/es/components/icon/assets/logo_ibm_mono'
import { icon as logo_kafka } from '@elastic/eui/es/components/icon/assets/logo_kafka'
import { icon as logo_kibana } from '@elastic/eui/es/components/icon/assets/logo_kibana'
import { icon as logo_kubernetes } from '@elastic/eui/es/components/icon/assets/logo_kubernetes'
import { icon as logo_logging } from '@elastic/eui/es/components/icon/assets/logo_logging'
import { icon as logo_logstash } from '@elastic/eui/es/components/icon/assets/logo_logstash'
import { icon as logo_maps } from '@elastic/eui/es/components/icon/assets/logo_maps'
import { icon as logo_memcached } from '@elastic/eui/es/components/icon/assets/logo_memcached'
import { icon as logo_metrics } from '@elastic/eui/es/components/icon/assets/logo_metrics'
import { icon as logo_mongodb } from '@elastic/eui/es/components/icon/assets/logo_mongodb'
import { icon as logo_mysql } from '@elastic/eui/es/components/icon/assets/logo_mysql'
import { icon as logo_nginx } from '@elastic/eui/es/components/icon/assets/logo_nginx'
import { icon as logo_observability } from '@elastic/eui/es/components/icon/assets/logo_observability'
import { icon as logo_osquery } from '@elastic/eui/es/components/icon/assets/logo_osquery'
import { icon as logo_php } from '@elastic/eui/es/components/icon/assets/logo_php'
import { icon as logo_postgres } from '@elastic/eui/es/components/icon/assets/logo_postgres'
import { icon as logo_prometheus } from '@elastic/eui/es/components/icon/assets/logo_prometheus'
import { icon as logo_rabbitmq } from '@elastic/eui/es/components/icon/assets/logo_rabbitmq'
import { icon as logo_redis } from '@elastic/eui/es/components/icon/assets/logo_redis'
import { icon as logo_security } from '@elastic/eui/es/components/icon/assets/logo_security'
import { icon as logo_site_search } from '@elastic/eui/es/components/icon/assets/logo_site_search'
import { icon as logo_sketch } from '@elastic/eui/es/components/icon/assets/logo_sketch'
import { icon as logo_slack } from '@elastic/eui/es/components/icon/assets/logo_slack'
import { icon as logo_uptime } from '@elastic/eui/es/components/icon/assets/logo_uptime'
import { icon as logo_vulnerability_management } from '@elastic/eui/es/components/icon/assets/logo_vulnerability_management'
import { icon as logo_webhook } from '@elastic/eui/es/components/icon/assets/logo_webhook'
import { icon as logo_windows } from '@elastic/eui/es/components/icon/assets/logo_windows'
import { icon as logo_workplace_search } from '@elastic/eui/es/components/icon/assets/logo_workplace_search'
import { icon as logstash_filter } from '@elastic/eui/es/components/icon/assets/logstash_filter'
import { icon as logstash_if } from '@elastic/eui/es/components/icon/assets/logstash_if'
import { icon as logstash_input } from '@elastic/eui/es/components/icon/assets/logstash_input'
import { icon as logstash_output } from '@elastic/eui/es/components/icon/assets/logstash_output'
import { icon as logstash_queue } from '@elastic/eui/es/components/icon/assets/logstash_queue'
import { icon as magnet } from '@elastic/eui/es/components/icon/assets/magnet'
import { icon as magnifyWithExclamation } from '@elastic/eui/es/components/icon/assets/magnifyWithExclamation'
import { icon as magnifyWithMinus } from '@elastic/eui/es/components/icon/assets/magnifyWithMinus'
import { icon as magnifyWithPlus } from '@elastic/eui/es/components/icon/assets/magnifyWithPlus'
import { icon as map_marker } from '@elastic/eui/es/components/icon/assets/map_marker'
import { icon as memory } from '@elastic/eui/es/components/icon/assets/memory'
import { icon as menu } from '@elastic/eui/es/components/icon/assets/menu'
import { icon as menuDown } from '@elastic/eui/es/components/icon/assets/menuDown'
import { icon as menuLeft } from '@elastic/eui/es/components/icon/assets/menuLeft'
import { icon as menuRight } from '@elastic/eui/es/components/icon/assets/menuRight'
import { icon as menuUp } from '@elastic/eui/es/components/icon/assets/menuUp'
import { icon as merge } from '@elastic/eui/es/components/icon/assets/merge'
import { icon as minimize } from '@elastic/eui/es/components/icon/assets/minimize'
import { icon as minus } from '@elastic/eui/es/components/icon/assets/minus'
import { icon as minus_in_circle } from '@elastic/eui/es/components/icon/assets/minus_in_circle'
import { icon as minus_in_circle_filled } from '@elastic/eui/es/components/icon/assets/minus_in_circle_filled'
import { icon as minus_in_square } from '@elastic/eui/es/components/icon/assets/minus_in_square'
import { icon as ml_classification_job } from '@elastic/eui/es/components/icon/assets/ml_classification_job'
import { icon as ml_create_advanced_job } from '@elastic/eui/es/components/icon/assets/ml_create_advanced_job'
import { icon as ml_create_generic_job } from '@elastic/eui/es/components/icon/assets/ml_create_generic_job'
import { icon as ml_create_geo_job } from '@elastic/eui/es/components/icon/assets/ml_create_geo_job'
import { icon as ml_create_multi_metric_job } from '@elastic/eui/es/components/icon/assets/ml_create_multi_metric_job'
import { icon as ml_create_population_job } from '@elastic/eui/es/components/icon/assets/ml_create_population_job'
import { icon as ml_create_single_metric_job } from '@elastic/eui/es/components/icon/assets/ml_create_single_metric_job'
import { icon as ml_data_visualizer } from '@elastic/eui/es/components/icon/assets/ml_data_visualizer'
import { icon as ml_outlier_detection_job } from '@elastic/eui/es/components/icon/assets/ml_outlier_detection_job'
import { icon as ml_regression_job } from '@elastic/eui/es/components/icon/assets/ml_regression_job'
import { icon as mobile } from '@elastic/eui/es/components/icon/assets/mobile'
import { icon as moon } from '@elastic/eui/es/components/icon/assets/moon'
import { icon as move } from '@elastic/eui/es/components/icon/assets/move'
import { icon as namespace } from '@elastic/eui/es/components/icon/assets/namespace'
import { icon as nested } from '@elastic/eui/es/components/icon/assets/nested'
import { icon as new_chat } from '@elastic/eui/es/components/icon/assets/new_chat'
import { icon as node } from '@elastic/eui/es/components/icon/assets/node'
import { icon as number } from '@elastic/eui/es/components/icon/assets/number'
import { icon as offline } from '@elastic/eui/es/components/icon/assets/offline'
import { icon as online } from '@elastic/eui/es/components/icon/assets/online'
import { icon as packageIcon } from '@elastic/eui/es/components/icon/assets/package'
import { icon as pageSelect } from '@elastic/eui/es/components/icon/assets/pageSelect'
import { icon as pagesSelect } from '@elastic/eui/es/components/icon/assets/pagesSelect'
import { icon as paint } from '@elastic/eui/es/components/icon/assets/paint'
import { icon as palette } from '@elastic/eui/es/components/icon/assets/palette'
import { icon as paper_clip } from '@elastic/eui/es/components/icon/assets/paper_clip'
import { icon as partial } from '@elastic/eui/es/components/icon/assets/partial'
import { icon as pause } from '@elastic/eui/es/components/icon/assets/pause'
import { icon as payment } from '@elastic/eui/es/components/icon/assets/payment'
import { icon as pencil } from '@elastic/eui/es/components/icon/assets/pencil'
import { icon as percent } from '@elastic/eui/es/components/icon/assets/percent'
import { icon as pin } from '@elastic/eui/es/components/icon/assets/pin'
import { icon as pin_filled } from '@elastic/eui/es/components/icon/assets/pin_filled'
import { icon as pipeBreaks } from '@elastic/eui/es/components/icon/assets/pipeBreaks'
import { icon as pipeNoBreaks } from '@elastic/eui/es/components/icon/assets/pipeNoBreaks'
import { icon as pivot } from '@elastic/eui/es/components/icon/assets/pivot'
import { icon as play } from '@elastic/eui/es/components/icon/assets/play'
import { icon as playFilled } from '@elastic/eui/es/components/icon/assets/playFilled'
import { icon as plugs } from '@elastic/eui/es/components/icon/assets/plugs'
import { icon as plus } from '@elastic/eui/es/components/icon/assets/plus'
import { icon as plus_in_circle } from '@elastic/eui/es/components/icon/assets/plus_in_circle'
import { icon as plus_in_circle_filled } from '@elastic/eui/es/components/icon/assets/plus_in_circle_filled'
import { icon as plus_in_square } from '@elastic/eui/es/components/icon/assets/plus_in_square'
import { icon as popout } from '@elastic/eui/es/components/icon/assets/popout'
import { icon as push } from '@elastic/eui/es/components/icon/assets/push'
import { icon as question } from '@elastic/eui/es/components/icon/assets/question'
import { icon as quote } from '@elastic/eui/es/components/icon/assets/quote'
import { icon as readOnly } from '@elastic/eui/es/components/icon/assets/readOnly'
import { icon as refresh } from '@elastic/eui/es/components/icon/assets/refresh'
import { icon as reporter } from '@elastic/eui/es/components/icon/assets/reporter'
import { icon as return_key } from '@elastic/eui/es/components/icon/assets/return_key'
import { icon as save } from '@elastic/eui/es/components/icon/assets/save'
import { icon as scale } from '@elastic/eui/es/components/icon/assets/scale'
import { icon as search } from '@elastic/eui/es/components/icon/assets/search'
import { icon as section } from '@elastic/eui/es/components/icon/assets/section'
import { icon as securitySignal } from '@elastic/eui/es/components/icon/assets/securitySignal'
import { icon as securitySignalDetected } from '@elastic/eui/es/components/icon/assets/securitySignalDetected'
import { icon as securitySignalResolved } from '@elastic/eui/es/components/icon/assets/securitySignalResolved'
import { icon as sessionViewer } from '@elastic/eui/es/components/icon/assets/sessionViewer'
import { icon as shard } from '@elastic/eui/es/components/icon/assets/shard'
import { icon as share } from '@elastic/eui/es/components/icon/assets/share'
import { icon as single_metric_viewer } from '@elastic/eui/es/components/icon/assets/single_metric_viewer'
import { icon as snowflake } from '@elastic/eui/es/components/icon/assets/snowflake'
import { icon as sortAscending } from '@elastic/eui/es/components/icon/assets/sortAscending'
import { icon as sortDescending } from '@elastic/eui/es/components/icon/assets/sortDescending'
import { icon as sortLeft } from '@elastic/eui/es/components/icon/assets/sortLeft'
import { icon as sortRight } from '@elastic/eui/es/components/icon/assets/sortRight'
import { icon as sort_down } from '@elastic/eui/es/components/icon/assets/sort_down'
import { icon as sort_up } from '@elastic/eui/es/components/icon/assets/sort_up'
import { icon as sortable } from '@elastic/eui/es/components/icon/assets/sortable'
import { icon as spaces } from '@elastic/eui/es/components/icon/assets/spaces'
import { icon as sparkles } from '@elastic/eui/es/components/icon/assets/sparkles'
import { icon as starPlusEmpty } from '@elastic/eui/es/components/icon/assets/starPlusEmpty'
import { icon as starPlusFilled } from '@elastic/eui/es/components/icon/assets/starPlusFilled'
import { icon as star_empty } from '@elastic/eui/es/components/icon/assets/star_empty'
import { icon as star_empty_space } from '@elastic/eui/es/components/icon/assets/star_empty_space'
import { icon as star_filled } from '@elastic/eui/es/components/icon/assets/star_filled'
import { icon as star_filled_space } from '@elastic/eui/es/components/icon/assets/star_filled_space'
import { icon as star_minus_empty } from '@elastic/eui/es/components/icon/assets/star_minus_empty'
import { icon as star_minus_filled } from '@elastic/eui/es/components/icon/assets/star_minus_filled'
import { icon as stats } from '@elastic/eui/es/components/icon/assets/stats'
import { icon as stop } from '@elastic/eui/es/components/icon/assets/stop'
import { icon as stop_filled } from '@elastic/eui/es/components/icon/assets/stop_filled'
import { icon as stop_slash } from '@elastic/eui/es/components/icon/assets/stop_slash'
import { icon as storage } from '@elastic/eui/es/components/icon/assets/storage'
import { icon as streams_classic } from '@elastic/eui/es/components/icon/assets/streams_classic'
import { icon as streams_wired } from '@elastic/eui/es/components/icon/assets/streams_wired'
import { icon as string } from '@elastic/eui/es/components/icon/assets/string'
import { icon as submodule } from '@elastic/eui/es/components/icon/assets/submodule'
import { icon as sun } from '@elastic/eui/es/components/icon/assets/sun'
import { icon as swatch_input } from '@elastic/eui/es/components/icon/assets/swatch_input'
import { icon as symlink } from '@elastic/eui/es/components/icon/assets/symlink'
import { icon as tableOfContents } from '@elastic/eui/es/components/icon/assets/tableOfContents'
import { icon as table_density_compact } from '@elastic/eui/es/components/icon/assets/table_density_compact'
import { icon as table_density_expanded } from '@elastic/eui/es/components/icon/assets/table_density_expanded'
import { icon as table_density_normal } from '@elastic/eui/es/components/icon/assets/table_density_normal'
import { icon as tag } from '@elastic/eui/es/components/icon/assets/tag'
import { icon as tear } from '@elastic/eui/es/components/icon/assets/tear'
import { icon as temperature } from '@elastic/eui/es/components/icon/assets/temperature'
import { icon as thumbDown } from '@elastic/eui/es/components/icon/assets/thumbDown'
import { icon as thumbUp } from '@elastic/eui/es/components/icon/assets/thumbUp'
import { icon as timeRefresh } from '@elastic/eui/es/components/icon/assets/timeRefresh'
import { icon as timeline } from '@elastic/eui/es/components/icon/assets/timeline'
import { icon as timelineWithArrow } from '@elastic/eui/es/components/icon/assets/timelineWithArrow'
import { icon as timeslider } from '@elastic/eui/es/components/icon/assets/timeslider'
import { icon as tokenAlias } from '@elastic/eui/es/components/icon/assets/tokenAlias'
import { icon as tokenAnnotation } from '@elastic/eui/es/components/icon/assets/tokenAnnotation'
import { icon as tokenArray } from '@elastic/eui/es/components/icon/assets/tokenArray'
import { icon as tokenBinary } from '@elastic/eui/es/components/icon/assets/tokenBinary'
import { icon as tokenBoolean } from '@elastic/eui/es/components/icon/assets/tokenBoolean'
import { icon as tokenClass } from '@elastic/eui/es/components/icon/assets/tokenClass'
import { icon as tokenCompletionSuggester } from '@elastic/eui/es/components/icon/assets/tokenCompletionSuggester'
import { icon as tokenConstant } from '@elastic/eui/es/components/icon/assets/tokenConstant'
import { icon as tokenDate } from '@elastic/eui/es/components/icon/assets/tokenDate'
import { icon as tokenDimension } from '@elastic/eui/es/components/icon/assets/tokenDimension'
import { icon as tokenElement } from '@elastic/eui/es/components/icon/assets/tokenElement'
import { icon as tokenEnum } from '@elastic/eui/es/components/icon/assets/tokenEnum'
import { icon as tokenEnumMember } from '@elastic/eui/es/components/icon/assets/tokenEnumMember'
import { icon as tokenEvent } from '@elastic/eui/es/components/icon/assets/tokenEvent'
import { icon as tokenException } from '@elastic/eui/es/components/icon/assets/tokenException'
import { icon as tokenField } from '@elastic/eui/es/components/icon/assets/tokenField'
import { icon as tokenFile } from '@elastic/eui/es/components/icon/assets/tokenFile'
import { icon as tokenFlattened } from '@elastic/eui/es/components/icon/assets/tokenFlattened'
import { icon as tokenFunction } from '@elastic/eui/es/components/icon/assets/tokenFunction'
import { icon as tokenGeo } from '@elastic/eui/es/components/icon/assets/tokenGeo'
import { icon as tokenHistogram } from '@elastic/eui/es/components/icon/assets/tokenHistogram'
import { icon as tokenIP } from '@elastic/eui/es/components/icon/assets/tokenIP'
import { icon as tokenInterface } from '@elastic/eui/es/components/icon/assets/tokenInterface'
import { icon as tokenJoin } from '@elastic/eui/es/components/icon/assets/tokenJoin'
import { icon as tokenKey } from '@elastic/eui/es/components/icon/assets/tokenKey'
import { icon as tokenKeyword } from '@elastic/eui/es/components/icon/assets/tokenKeyword'
import { icon as tokenMethod } from '@elastic/eui/es/components/icon/assets/tokenMethod'
import { icon as tokenMetricCounter } from '@elastic/eui/es/components/icon/assets/tokenMetricCounter'
import { icon as tokenMetricGauge } from '@elastic/eui/es/components/icon/assets/tokenMetricGauge'
import { icon as tokenModule } from '@elastic/eui/es/components/icon/assets/tokenModule'
import { icon as tokenNamespace } from '@elastic/eui/es/components/icon/assets/tokenNamespace'
import { icon as tokenNested } from '@elastic/eui/es/components/icon/assets/tokenNested'
import { icon as tokenNull } from '@elastic/eui/es/components/icon/assets/tokenNull'
import { icon as tokenNumber } from '@elastic/eui/es/components/icon/assets/tokenNumber'
import { icon as tokenObject } from '@elastic/eui/es/components/icon/assets/tokenObject'
import { icon as tokenOperator } from '@elastic/eui/es/components/icon/assets/tokenOperator'
import { icon as tokenPackage } from '@elastic/eui/es/components/icon/assets/tokenPackage'
import { icon as tokenParameter } from '@elastic/eui/es/components/icon/assets/tokenParameter'
import { icon as tokenPercolator } from '@elastic/eui/es/components/icon/assets/tokenPercolator'
import { icon as tokenProperty } from '@elastic/eui/es/components/icon/assets/tokenProperty'
import { icon as tokenRange } from '@elastic/eui/es/components/icon/assets/tokenRange'
import { icon as tokenRankFeature } from '@elastic/eui/es/components/icon/assets/tokenRankFeature'
import { icon as tokenRankFeatures } from '@elastic/eui/es/components/icon/assets/tokenRankFeatures'
import { icon as tokenRepo } from '@elastic/eui/es/components/icon/assets/tokenRepo'
import { icon as tokenSearchType } from '@elastic/eui/es/components/icon/assets/tokenSearchType'
import { icon as tokenSemanticText } from '@elastic/eui/es/components/icon/assets/tokenSemanticText'
import { icon as tokenShape } from '@elastic/eui/es/components/icon/assets/tokenShape'
import { icon as tokenString } from '@elastic/eui/es/components/icon/assets/tokenString'
import { icon as tokenStruct } from '@elastic/eui/es/components/icon/assets/tokenStruct'
import { icon as tokenSymbol } from '@elastic/eui/es/components/icon/assets/tokenSymbol'
import { icon as tokenTag } from '@elastic/eui/es/components/icon/assets/tokenTag'
import { icon as tokenText } from '@elastic/eui/es/components/icon/assets/tokenText'
import { icon as tokenTokenCount } from '@elastic/eui/es/components/icon/assets/tokenTokenCount'
import { icon as tokenVariable } from '@elastic/eui/es/components/icon/assets/tokenVariable'
import { icon as tokenVectorDense } from '@elastic/eui/es/components/icon/assets/tokenVectorDense'
import { icon as tokenVectorSparse } from '@elastic/eui/es/components/icon/assets/tokenVectorSparse'
import { icon as training } from '@elastic/eui/es/components/icon/assets/training'
import { icon as transitionLeftIn } from '@elastic/eui/es/components/icon/assets/transitionLeftIn'
import { icon as transitionLeftOut } from '@elastic/eui/es/components/icon/assets/transitionLeftOut'
import { icon as transitionTopIn } from '@elastic/eui/es/components/icon/assets/transitionTopIn'
import { icon as transitionTopOut } from '@elastic/eui/es/components/icon/assets/transitionTopOut'
import { icon as trash } from '@elastic/eui/es/components/icon/assets/trash'
import { icon as unfold } from '@elastic/eui/es/components/icon/assets/unfold'
import { icon as unlink } from '@elastic/eui/es/components/icon/assets/unlink'
import { icon as user } from '@elastic/eui/es/components/icon/assets/user'
import { icon as users } from '@elastic/eui/es/components/icon/assets/users'
import { icon as vector } from '@elastic/eui/es/components/icon/assets/vector'
import { icon as videoPlayer } from '@elastic/eui/es/components/icon/assets/videoPlayer'
import { icon as vis_area } from '@elastic/eui/es/components/icon/assets/vis_area'
import { icon as vis_area_stacked } from '@elastic/eui/es/components/icon/assets/vis_area_stacked'
import { icon as vis_bar_horizontal } from '@elastic/eui/es/components/icon/assets/vis_bar_horizontal'
import { icon as vis_bar_horizontal_stacked } from '@elastic/eui/es/components/icon/assets/vis_bar_horizontal_stacked'
import { icon as vis_bar_vertical } from '@elastic/eui/es/components/icon/assets/vis_bar_vertical'
import { icon as vis_bar_vertical_stacked } from '@elastic/eui/es/components/icon/assets/vis_bar_vertical_stacked'
import { icon as vis_gauge } from '@elastic/eui/es/components/icon/assets/vis_gauge'
import { icon as vis_goal } from '@elastic/eui/es/components/icon/assets/vis_goal'
import { icon as vis_line } from '@elastic/eui/es/components/icon/assets/vis_line'
import { icon as vis_map_coordinate } from '@elastic/eui/es/components/icon/assets/vis_map_coordinate'
import { icon as vis_map_region } from '@elastic/eui/es/components/icon/assets/vis_map_region'
import { icon as vis_metric } from '@elastic/eui/es/components/icon/assets/vis_metric'
import { icon as vis_pie } from '@elastic/eui/es/components/icon/assets/vis_pie'
import { icon as vis_table } from '@elastic/eui/es/components/icon/assets/vis_table'
import { icon as vis_tag_cloud } from '@elastic/eui/es/components/icon/assets/vis_tag_cloud'
import { icon as vis_text } from '@elastic/eui/es/components/icon/assets/vis_text'
import { icon as vis_timelion } from '@elastic/eui/es/components/icon/assets/vis_timelion'
import { icon as vis_visual_builder } from '@elastic/eui/es/components/icon/assets/vis_visual_builder'
import { icon as warning } from '@elastic/eui/es/components/icon/assets/warning'
import { icon as warningFilled } from '@elastic/eui/es/components/icon/assets/warningFilled'
import { icon as web } from '@elastic/eui/es/components/icon/assets/web'
import { icon as wordWrap } from '@elastic/eui/es/components/icon/assets/wordWrap'
import { icon as wordWrapDisabled } from '@elastic/eui/es/components/icon/assets/wordWrapDisabled'
import { icon as wrench } from '@elastic/eui/es/components/icon/assets/wrench'

// Register all icons with both snake_case and camelCase names
appendIconComponentCache({
  accessibility,
  aggregate,
  alert,
  analyzeEvent,
  analyze_event,
  annotation,
  anomaly_chart,
  anomalyChart: anomaly_chart,
  anomaly_swim_lane,
  anomalySwimLane: anomaly_swim_lane,
  apm_trace,
  apmTrace: apm_trace,
  app_add_data,
  appAddData: app_add_data,
  app_advanced_settings,
  appAdvancedSettings: app_advanced_settings,
  app_agent,
  appAgent: app_agent,
  app_apm,
  appApm: app_apm,
  app_app_search,
  appAppSearch: app_app_search,
  app_auditbeat,
  appAuditbeat: app_auditbeat,
  app_canvas,
  appCanvas: app_canvas,
  app_cases,
  appCases: app_cases,
  app_code,
  appCode: app_code,
  app_console,
  appConsole: app_console,
  app_cross_cluster_replication,
  appCrossClusterReplication: app_cross_cluster_replication,
  app_dashboard,
  appDashboard: app_dashboard,
  app_devtools,
  appDevtools: app_devtools,
  app_discover,
  appDiscover: app_discover,
  app_ems,
  appEms: app_ems,
  app_filebeat,
  appFilebeat: app_filebeat,
  app_fleet,
  appFleet: app_fleet,
  app_gis,
  appGis: app_gis,
  app_graph,
  appGraph: app_graph,
  app_grok,
  appGrok: app_grok,
  app_heartbeat,
  appHeartbeat: app_heartbeat,
  app_index_management,
  appIndexManagement: app_index_management,
  app_index_pattern,
  appIndexPattern: app_index_pattern,
  app_index_rollup,
  appIndexRollup: app_index_rollup,
  app_lens,
  appLens: app_lens,
  app_logs,
  appLogs: app_logs,
  app_management,
  appManagement: app_management,
  app_metricbeat,
  appMetricbeat: app_metricbeat,
  app_metrics,
  appMetrics: app_metrics,
  app_ml,
  appMl: app_ml,
  app_monitoring,
  appMonitoring: app_monitoring,
  app_notebook,
  appNotebook: app_notebook,
  app_packetbeat,
  appPacketbeat: app_packetbeat,
  app_pipeline,
  appPipeline: app_pipeline,
  app_recently_viewed,
  appRecentlyViewed: app_recently_viewed,
  app_reporting,
  appReporting: app_reporting,
  app_saved_objects,
  appSavedObjects: app_saved_objects,
  app_search_profiler,
  appSearchProfiler: app_search_profiler,
  app_security,
  appSecurity: app_security,
  app_security_analytics,
  appSecurityAnalytics: app_security_analytics,
  app_spaces,
  appSpaces: app_spaces,
  app_sql,
  appSql: app_sql,
  app_timelion,
  appTimelion: app_timelion,
  app_upgrade_assistant,
  appUpgradeAssistant: app_upgrade_assistant,
  app_uptime,
  appUptime: app_uptime,
  app_users_roles,
  appUsersRoles: app_users_roles,
  app_visualize,
  appVisualize: app_visualize,
  app_vulnerability_management,
  appVulnerabilityManagement: app_vulnerability_management,
  app_watches,
  appWatches: app_watches,
  app_workflows,
  appWorkflows: app_workflows,
  app_workplace_search,
  appWorkplaceSearch: app_workplace_search,
  apps,
  arrowEnd,
  arrowStart,
  arrow_down,
  arrowDown: arrow_down,
  arrow_left,
  arrowLeft: arrow_left,
  arrow_right,
  arrowRight: arrow_right,
  arrow_up,
  arrowUp: arrow_up,
  article,
  asterisk,
  at,
  background_task,
  backgroundTask: background_task,
  bell,
  bellSlash,
  beta,
  bolt,
  boxes_horizontal,
  boxesHorizontal: boxes_horizontal,
  boxes_vertical,
  boxesVertical: boxes_vertical,
  branch,
  branchUser,
  broom,
  brush,
  bug,
  bullseye,
  calendar,
  change_point_detection,
  changePointDetection: change_point_detection,
  check,
  checkCircle,
  checkInCircleFilled,
  cheer,
  clickLeft,
  clickRight,
  clock,
  clockCounter,
  cloudDrizzle,
  cloudStormy,
  cloudSunny,
  cluster,
  code,
  color,
  comment,
  compute,
  console,
  container,
  continuityAbove,
  continuityAboveBelow,
  continuityBelow,
  continuityWithin,
  contrast,
  contrastHigh,
  controls,
  copy,
  copy_clipboard,
  copyClipboard: copy_clipboard,
  cross,
  crossInCircle,
  cross_in_circle,
  crosshairs,
  currency,
  cut,
  database,
  desktop,
  diff,
  document,
  documentEdit,
  documentation,
  documents,
  dot,
  dotInCircle,
  doubleArrowLeft,
  doubleArrowRight,
  download,
  editorDistributeHorizontal,
  editorDistributeVertical,
  editorItemAlignBottom,
  editorItemAlignCenter,
  editorItemAlignLeft,
  editorItemAlignMiddle,
  editorItemAlignRight,
  editorItemAlignTop,
  editorPositionBottomLeft,
  editorPositionBottomRight,
  editorPositionTopLeft,
  editorPositionTopRight,
  editor_align_center,
  editorAlignCenter: editor_align_center,
  editor_align_left,
  editorAlignLeft: editor_align_left,
  editor_align_right,
  editorAlignRight: editor_align_right,
  editor_bold,
  editorBold: editor_bold,
  editor_checklist,
  editorChecklist: editor_checklist,
  editor_heading,
  editorHeading: editor_heading,
  editor_italic,
  editorItalic: editor_italic,
  editor_link,
  editorLink: editor_link,
  editor_ordered_list,
  editorOrderedList: editor_ordered_list,
  editor_redo,
  editorRedo: editor_redo,
  editor_strike,
  editorStrike: editor_strike,
  editor_table,
  editorTable: editor_table,
  editor_underline,
  editorUnderline: editor_underline,
  editor_undo,
  editorUndo: editor_undo,
  editor_unordered_list,
  editorUnorderedList: editor_unordered_list,
  email,
  empty,
  endpoint,
  eql,
  eraser,
  error,
  errorFilled,
  esqlVis,
  exit,
  expand,
  expandMini,
  exportIcon,
  export: exportIcon,
  eye,
  eye_closed,
  eyeClosed: eye_closed,
  face_happy,
  faceHappy: face_happy,
  face_neutral,
  faceNeutral: face_neutral,
  face_sad,
  faceSad: face_sad,
  field_statistics,
  fieldStatistics: field_statistics,
  filter,
  filterExclude,
  filterIgnore,
  filterInCircle,
  filterInclude,
  flag,
  flask,
  fold,
  folder_check,
  folderCheck: folder_check,
  folder_closed,
  folderClosed: folder_closed,
  folder_exclamation,
  folderExclamation: folder_exclamation,
  folder_open,
  folderOpen: folder_open,
  frameNext,
  framePrevious,
  fullScreenExit,
  full_screen,
  fullScreen: full_screen,
  functionIcon,
  function: functionIcon,
  gear,
  globe,
  grab,
  grabOmnidirectional,
  grab_horizontal,
  grabHorizontal: grab_horizontal,
  gradient,
  grid,
  heart,
  heatmap,
  help,
  home,
  image,
  importIcon,
  import: importIcon,
  index,
  indexTemporary,
  index_close,
  indexClose: index_close,
  index_edit,
  indexEdit: index_edit,
  index_flush,
  indexFlush: index_flush,
  index_mapping,
  indexMapping: index_mapping,
  index_open,
  indexOpen: index_open,
  index_runtime,
  indexRuntime: index_runtime,
  index_settings,
  indexSettings: index_settings,
  infinity,
  info,
  inputOutput,
  inspect,
  invert,
  ip,
  issue,
  key,
  keyboard,
  kql_field,
  kqlField: kql_field,
  kql_function,
  kqlFunction: kql_function,
  kql_operand,
  kqlOperand: kql_operand,
  kql_selector,
  kqlSelector: kql_selector,
  kql_value,
  kqlValue: kql_value,
  kubernetesNode,
  kubernetesPod,
  launch,
  layers,
  lettering,
  lineDashed,
  lineDotted,
  lineSolid,
  link,
  list,
  list_add,
  listAdd: list_add,
  lock,
  lockOpen,
  log_pattern_analysis,
  logPatternAnalysis: log_pattern_analysis,
  log_rate_analysis,
  logRateAnalysis: log_rate_analysis,
  logo_aerospike,
  logoAerospike: logo_aerospike,
  logo_apache,
  logoApache: logo_apache,
  logo_app_search,
  logoAppSearch: logo_app_search,
  logo_aws,
  logoAws: logo_aws,
  logo_aws_mono,
  logoAwsMono: logo_aws_mono,
  logo_azure,
  logoAzure: logo_azure,
  logo_azure_mono,
  logoAzureMono: logo_azure_mono,
  logo_beats,
  logoBeats: logo_beats,
  logo_business_analytics,
  logoBusinessAnalytics: logo_business_analytics,
  logo_ceph,
  logoCeph: logo_ceph,
  logo_cloud,
  logoCloud: logo_cloud,
  logo_cloud_ece,
  logoCloudEce: logo_cloud_ece,
  logo_code,
  logoCode: logo_code,
  logo_codesandbox,
  logoCodesandbox: logo_codesandbox,
  logo_couchbase,
  logoCouchbase: logo_couchbase,
  logo_docker,
  logoDocker: logo_docker,
  logo_dropwizard,
  logoDropwizard: logo_dropwizard,
  logo_elastic,
  logoElastic: logo_elastic,
  logo_elastic_stack,
  logoElasticStack: logo_elastic_stack,
  logo_elasticsearch,
  logoElasticsearch: logo_elasticsearch,
  logo_enterprise_search,
  logoEnterpriseSearch: logo_enterprise_search,
  logo_etcd,
  logoEtcd: logo_etcd,
  logo_gcp,
  logoGcp: logo_gcp,
  logo_gcp_mono,
  logoGcpMono: logo_gcp_mono,
  logo_github,
  logoGithub: logo_github,
  logo_gmail,
  logoGmail: logo_gmail,
  logo_golang,
  logoGolang: logo_golang,
  logo_google_g,
  logoGoogleG: logo_google_g,
  logo_haproxy,
  logoHaproxy: logo_haproxy,
  logo_ibm,
  logoIbm: logo_ibm,
  logo_ibm_mono,
  logoIbmMono: logo_ibm_mono,
  logo_kafka,
  logoKafka: logo_kafka,
  logo_kibana,
  logoKibana: logo_kibana,
  logo_kubernetes,
  logoKubernetes: logo_kubernetes,
  logo_logging,
  logoLogging: logo_logging,
  logo_logstash,
  logoLogstash: logo_logstash,
  logo_maps,
  logoMaps: logo_maps,
  logo_memcached,
  logoMemcached: logo_memcached,
  logo_metrics,
  logoMetrics: logo_metrics,
  logo_mongodb,
  logoMongodb: logo_mongodb,
  logo_mysql,
  logoMysql: logo_mysql,
  logo_nginx,
  logoNginx: logo_nginx,
  logo_observability,
  logoObservability: logo_observability,
  logo_osquery,
  logoOsquery: logo_osquery,
  logo_php,
  logoPhp: logo_php,
  logo_postgres,
  logoPostgres: logo_postgres,
  logo_prometheus,
  logoPrometheus: logo_prometheus,
  logo_rabbitmq,
  logoRabbitmq: logo_rabbitmq,
  logo_redis,
  logoRedis: logo_redis,
  logo_security,
  logoSecurity: logo_security,
  logo_site_search,
  logoSiteSearch: logo_site_search,
  logo_sketch,
  logoSketch: logo_sketch,
  logo_slack,
  logoSlack: logo_slack,
  logo_uptime,
  logoUptime: logo_uptime,
  logo_vulnerability_management,
  logoVulnerabilityManagement: logo_vulnerability_management,
  logo_webhook,
  logoWebhook: logo_webhook,
  logo_windows,
  logoWindows: logo_windows,
  logo_workplace_search,
  logoWorkplaceSearch: logo_workplace_search,
  logstash_filter,
  logstashFilter: logstash_filter,
  logstash_if,
  logstashIf: logstash_if,
  logstash_input,
  logstashInput: logstash_input,
  logstash_output,
  logstashOutput: logstash_output,
  logstash_queue,
  logstashQueue: logstash_queue,
  magnet,
  magnifyWithExclamation,
  magnifyWithMinus,
  magnifyWithPlus,
  map_marker,
  mapMarker: map_marker,
  memory,
  menu,
  menuDown,
  menuLeft,
  menuRight,
  menuUp,
  merge,
  minimize,
  minus,
  minus_in_circle,
  minusInCircle: minus_in_circle,
  minus_in_circle_filled,
  minusInCircleFilled: minus_in_circle_filled,
  minus_in_square,
  minusInSquare: minus_in_square,
  ml_classification_job,
  mlClassificationJob: ml_classification_job,
  ml_create_advanced_job,
  mlCreateAdvancedJob: ml_create_advanced_job,
  ml_create_generic_job,
  mlCreateGenericJob: ml_create_generic_job,
  ml_create_geo_job,
  mlCreateGeoJob: ml_create_geo_job,
  ml_create_multi_metric_job,
  mlCreateMultiMetricJob: ml_create_multi_metric_job,
  ml_create_population_job,
  mlCreatePopulationJob: ml_create_population_job,
  ml_create_single_metric_job,
  mlCreateSingleMetricJob: ml_create_single_metric_job,
  ml_data_visualizer,
  mlDataVisualizer: ml_data_visualizer,
  ml_outlier_detection_job,
  mlOutlierDetectionJob: ml_outlier_detection_job,
  ml_regression_job,
  mlRegressionJob: ml_regression_job,
  mobile,
  moon,
  move,
  namespace,
  nested,
  new_chat,
  newChat: new_chat,
  node,
  number,
  offline,
  online,
  packageIcon,
  package: packageIcon,
  pageSelect,
  pagesSelect,
  paint,
  palette,
  paper_clip,
  paperClip: paper_clip,
  partial,
  pause,
  payment,
  pencil,
  percent,
  pin,
  pin_filled,
  pinFilled: pin_filled,
  pipeBreaks,
  pipeNoBreaks,
  pivot,
  play,
  playFilled,
  plugs,
  plus,
  plus_in_circle,
  plusInCircle: plus_in_circle,
  plus_in_circle_filled,
  plusInCircleFilled: plus_in_circle_filled,
  plus_in_square,
  plusInSquare: plus_in_square,
  popout,
  push,
  question,
  quote,
  readOnly,
  refresh,
  reporter,
  return_key,
  returnKey: return_key,
  save,
  scale,
  search,
  section,
  securitySignal,
  securitySignalDetected,
  securitySignalResolved,
  sessionViewer,
  shard,
  share,
  single_metric_viewer,
  singleMetricViewer: single_metric_viewer,
  snowflake,
  sortAscending,
  sortDescending,
  sortLeft,
  sortRight,
  sort_down,
  sortDown: sort_down,
  sort_up,
  sortUp: sort_up,
  sortable,
  spaces,
  sparkles,
  starPlusEmpty,
  starPlusFilled,
  star_empty,
  starEmpty: star_empty,
  star_empty_space,
  starEmptySpace: star_empty_space,
  star_filled,
  starFilled: star_filled,
  star_filled_space,
  starFilledSpace: star_filled_space,
  star_minus_empty,
  starMinusEmpty: star_minus_empty,
  star_minus_filled,
  starMinusFilled: star_minus_filled,
  stats,
  stop,
  stop_filled,
  stopFilled: stop_filled,
  stop_slash,
  stopSlash: stop_slash,
  storage,
  streams_classic,
  streamsClassic: streams_classic,
  streams_wired,
  streamsWired: streams_wired,
  string,
  submodule,
  sun,
  swatch_input,
  swatchInput: swatch_input,
  symlink,
  tableOfContents,
  table_density_compact,
  tableDensityCompact: table_density_compact,
  table_density_expanded,
  tableDensityExpanded: table_density_expanded,
  table_density_normal,
  tableDensityNormal: table_density_normal,
  tag,
  tear,
  temperature,
  thumbDown,
  thumbUp,
  timeRefresh,
  timeline,
  timelineWithArrow,
  timeslider,
  tokenAlias,
  tokenAnnotation,
  tokenArray,
  tokenBinary,
  tokenBoolean,
  tokenClass,
  tokenCompletionSuggester,
  tokenConstant,
  tokenDate,
  tokenDimension,
  tokenElement,
  tokenEnum,
  tokenEnumMember,
  tokenEvent,
  tokenException,
  tokenField,
  tokenFile,
  tokenFlattened,
  tokenFunction,
  tokenGeo,
  tokenHistogram,
  tokenIP,
  tokenInterface,
  tokenJoin,
  tokenKey,
  tokenKeyword,
  tokenMethod,
  tokenMetricCounter,
  tokenMetricGauge,
  tokenModule,
  tokenNamespace,
  tokenNested,
  tokenNull,
  tokenNumber,
  tokenObject,
  tokenOperator,
  tokenPackage,
  tokenParameter,
  tokenPercolator,
  tokenProperty,
  tokenRange,
  tokenRankFeature,
  tokenRankFeatures,
  tokenRepo,
  tokenSearchType,
  tokenSemanticText,
  tokenShape,
  tokenString,
  tokenStruct,
  tokenSymbol,
  tokenTag,
  tokenText,
  tokenTokenCount,
  tokenVariable,
  tokenVectorDense,
  tokenVectorSparse,
  training,
  transitionLeftIn,
  transitionLeftOut,
  transitionTopIn,
  transitionTopOut,
  trash,
  unfold,
  unlink,
  user,
  users,
  vector,
  videoPlayer,
  vis_area,
  visArea: vis_area,
  vis_area_stacked,
  visAreaStacked: vis_area_stacked,
  vis_bar_horizontal,
  visBarHorizontal: vis_bar_horizontal,
  vis_bar_horizontal_stacked,
  visBarHorizontalStacked: vis_bar_horizontal_stacked,
  vis_bar_vertical,
  visBarVertical: vis_bar_vertical,
  vis_bar_vertical_stacked,
  visBarVerticalStacked: vis_bar_vertical_stacked,
  vis_gauge,
  visGauge: vis_gauge,
  vis_goal,
  visGoal: vis_goal,
  vis_line,
  visLine: vis_line,
  vis_map_coordinate,
  visMapCoordinate: vis_map_coordinate,
  vis_map_region,
  visMapRegion: vis_map_region,
  vis_metric,
  visMetric: vis_metric,
  vis_pie,
  visPie: vis_pie,
  vis_table,
  visTable: vis_table,
  vis_tag_cloud,
  visTagCloud: vis_tag_cloud,
  vis_text,
  visText: vis_text,
  vis_timelion,
  visTimelion: vis_timelion,
  vis_visual_builder,
  visVisualBuilder: vis_visual_builder,
  warning,
  warningFilled,
  web,
  wordWrap,
  wordWrapDisabled,
  wrench,
})

// Register EUI aliases (e.g., 'discuss' -> comment, 'newChat' -> plus_in_circle)
// These come from @elastic/eui/es/components/icon/icon_map.js
appendIconComponentCache({
  'addDataApp': app_add_data,
  'advancedSettingsApp': app_advanced_settings,
  'agentApp': app_fleet,
  'alert': warning,
  'apmApp': app_apm,
  'appSearchApp': app_app_search,
  'auditbeatApp': app_auditbeat,
  'beaker': flask,
  'boxesHorizontal': boxes_vertical,
  'canvasApp': app_canvas,
  'casesApp': app_cases,
  'classificationJob': ml_classification_job,
  'codeApp': app_code,
  'consoleApp': app_console,
  'controlsHorizontal': controls,
  'controlsVertical': controls,
  'copyClipboard': copy,
  'createAdvancedJob': ml_create_advanced_job,
  'createGenericJob': ml_create_generic_job,
  'createGeoJob': ml_create_geo_job,
  'createMultiMetricJob': ml_create_multi_metric_job,
  'createPopulationJob': ml_create_population_job,
  'createSingleMetricJob': ml_create_single_metric_job,
  'crossClusterReplicationApp': app_cross_cluster_replication,
  'dashboardApp': app_dashboard,
  'dataVisualizer': ml_data_visualizer,
  'devToolsApp': app_devtools,
  'discoverApp': app_discover,
  'discuss': comment,
  'documentEdit': pencil,
  'editorCodeBlock': code,
  'editorComment': comment,
  'editorLink': link,
  'editorTable': vis_table,
  'editorUnorderedList': list,
  'emsApp': app_ems,
  'expandMini': expand,
  'exportAction': exportIcon,
  'filebeatApp': app_filebeat,
  'filterInCircle': filter,
  'fleetApp': app_agent,
  'gisApp': app_gis,
  'graphApp': app_graph,
  'grokApp': app_grok,
  'heartbeatApp': app_heartbeat,
  'importAction': importIcon,
  'indexManagementApp': app_index_management,
  'indexPatternApp': app_index_pattern,
  'indexRollupApp': app_index_rollup,
  'lensApp': app_lens,
  'lettering': vis_text,
  'listAdd': plus_in_circle,
  'logoAWS': logo_aws,
  'logoAWSMono': logo_aws_mono,
  'logoCloudEnterprise': logo_cloud_ece,
  'logoGCP': logo_gcp,
  'logoGCPMono': logo_gcp_mono,
  'logoHAproxy': logo_haproxy,
  'logoIBM': logo_ibm,
  'logoIBMMono': logo_ibm_mono,
  'logoMySQL': logo_mysql,
  'logsApp': app_logs,
  'machineLearningApp': app_ml,
  'managementApp': app_management,
  'metricbeatApp': app_metricbeat,
  'metricsApp': app_metrics,
  'minusInCircleFilled': minus_in_circle,
  'monitoringApp': app_monitoring,
  'newChat': plus_in_circle,
  'notebookApp': app_notebook,
  'outlierDetectionJob': ml_outlier_detection_job,
  'packetbeatApp': app_packetbeat,
  'pipelineApp': app_pipeline,
  'playFilled': play,
  'plusInCircleFilled': plus_in_circle,
  'recentlyViewedApp': app_recently_viewed,
  'regressionJob': ml_regression_job,
  'reportingApp': app_reporting,
  'savedObjectsApp': app_saved_objects,
  'searchProfilerApp': app_search_profiler,
  'securityAnalyticsApp': app_security_analytics,
  'securityApp': app_security,
  'spacesApp': app_spaces,
  'sqlApp': app_sql,
  'submodule': merge,
  'tableDensityNormal': vis_table,
  'timelionApp': app_timelion,
  'upgradeAssistantApp': app_upgrade_assistant,
  'uptimeApp': app_uptime,
  'userAvatar': user,
  'usersRolesApp': app_users_roles,
  'visVega': code,
  'visualizeApp': app_visualize,
  'vulnerabilityManagementApp': app_vulnerability_management,
  'watchesApp': app_watches,
  'workflowsApp': app_workflows,
  'workplaceSearchApp': app_workplace_search,
})

// All 520 EUI icons + 97 aliases are now registered
